// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b2c20ae091a272c0 "STUDIO FINITY", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * timeLabelColor?: string // Time Label Color
 * timeLabelFont?: any // Time Label Font
 * statusRules?: {label: string, startHour: number, endHour: number[] // Status Rules
 * background?: string // Background
 * radius?: number // Radius
 * timeFont?: any // Time Font
 * timeSize?: number // Time Size
 * timeColor?: string // Time Color
 * statusFont?: any // Status Font
 * statusSize?: number // Status Size
 * statusPhraseColor?: string // Status Phrase Color
 * statusLabelColor?: string // Status Label Color
 * statusLabelFont?: any // Status Label Font
 * phraseColor?: string // Phrase Color
 * statusLabelText?: string // Status Label Text
 * replayAnimation?: boolean // Replay Animation
 * scrambleDuration?: number // Scramble Duration
 * scrambleChars?: string // Scramble Chars
 * _24HourTime?: boolean // 24-Hour Time
 * bottomPadding?: number // Bottom Padding
}} Props

 */
import { routes } from "./chunks/chunk-YRAVOFDK.js";

// virtual:denver-time-status
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/0Y0jL7AzfuJapZ1TmCn3/y4whHx0eXUIYTQPAPDIT/DenverTimeStatus.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState, useRef, startTransition } from "react";
import { addPropertyControls, ControlType } from "unframer";
import { useInView } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function TimeWithFade({ time, fontSize, color }) {
	return (
		<span
			style={{
				fontVariantNumeric: "tabular-nums",
			}}
		>
			{time.split("").map((char, i) => (
				<span
					style={{
						display: "inline-block",
						minWidth: char.match(/\d/) ? fontSize * 0.6 : void 0,
						textAlign: "center",
						color,
						fontSize,
					}}
				>
					{char}
				</span>
			))}
		</span>
	);
}
function DenverTimeStatus(props) {
	const {
		background,
		borderRadius,
		timeFont,
		timeFontSize,
		timeColor,
		timeLabelFont,
		statusFont,
		statusFontSize,
		statusColor,
		statusLabelColor,
		statusLabelFont,
		statusPhraseColor,
		style,
		scrambleDuration,
		scrambleChars,
	} = props;
	const [now, setNow] = useState(/* @__PURE__ */ new Date());
	const rootRef = useRef(null);
	const inView = useInView(rootRef, {
		once: false,
		margin: "-10% 0px",
	});
	useEffect(() => {
		const interval = setInterval(() => {
			startTransition(() => setNow(/* @__PURE__ */ new Date()));
		}, 1e3);
		return () => clearInterval(interval);
	}, []);
	function getDenverTime(date) {
		try {
			return new Date(
				date.toLocaleString("en-US", {
					timeZone: "America/Denver",
				}),
			);
		} catch {
			return date;
		}
	}
	const denverTime = getDenverTime(now);
	const hours = denverTime.getHours();
	const minutes = denverTime.getMinutes();
	let formatted = denverTime.toLocaleTimeString([], {
		hour: "2-digit",
		minute: "2-digit",
		second: "2-digit",
		hour12: props.use24Hour === true ? false : true,
	});
	let timePart = formatted;
	let ampmPart = "";
	if (!props.use24Hour) {
		const match = formatted.match(/(.*?)([AP]M)$/i);
		if (match) {
			timePart = match[1].trim();
			ampmPart = match[2];
		}
	}
	const statusRules = props.statusRules || [
		{
			label: "Making coffee",
			startHour: 6,
			endHour: 9,
		},
		{
			label: "Grabbing lunch",
			startHour: 12,
			endHour: 13,
		},
		{
			label: "Reading a book",
			startHour: 17,
			endHour: 24,
		},
		{
			label: "Working",
			startHour: 9,
			endHour: 12,
		},
		{
			label: "Working",
			startHour: 13,
			endHour: 17,
		},
	];
	const statuses = Array.from(new Set(statusRules.map((r) => r.label)));
	function getCurrentStatus(hours2) {
		const rule = statusRules.find((r) => {
			if (r.endHour < r.startHour) {
				return hours2 >= r.startHour || hours2 < r.endHour;
			}
			return hours2 >= r.startHour && hours2 < r.endHour;
		});
		return rule ? rule.label : statuses[0];
	}
	const showingStatus = getCurrentStatus(hours);
	const [scrambled, setScrambled] = useState("");
	const scrambleTimeout = useRef(null);
	function scrambleText(target, duration, interval = 30, chars) {
		let frame = 0;
		const totalFrames = Math.floor(duration / interval);
		if (scrambleTimeout.current) clearTimeout(scrambleTimeout.current);
		function step() {
			frame++;
			let scrambledText = "";
			for (let i = 0; i < target.length; i++) {
				if (frame < totalFrames) {
					scrambledText += chars[Math.floor(Math.random() * chars.length)];
				} else {
					scrambledText += target[i];
				}
			}
			setScrambled(scrambledText);
			if (frame < totalFrames) {
				scrambleTimeout.current = __unframerWindow.setTimeout(step, interval);
			} else {
				setScrambled(target);
			}
		}
		step();
	}
	useEffect(() => {
		if (inView)
			scrambleText(showingStatus, scrambleDuration, 30, scrambleChars);
	}, [inView, showingStatus, scrambleDuration, scrambleChars]);
	useEffect(() => {
		if (props.replayAnimation && inView)
			scrambleText(showingStatus, scrambleDuration, 30, scrambleChars);
	}, [props.replayAnimation, scrambleDuration, scrambleChars]);
	useEffect(
		() => () =>
			scrambleTimeout.current && clearTimeout(scrambleTimeout.current),
		[],
	);
	return (
		<div
			ref={rootRef}
			style={{
				...style,
				background,
				borderRadius,
				padding: 0,
				paddingBottom: props.bottomPadding,
				minWidth: 220,
				minHeight: 100,
				display: "flex",
				flexDirection: "column",
				alignItems: "flex-start",
				justifyContent: "center",
				gap: 12,
				textAlign: "left",
			}}
		>
			<span
				style={{
					...timeFont,
					fontSize: timeFontSize,
					width: "100%",
					display: "flex",
					flexDirection: "column",
					textAlign: "left",
					gap: 4,
				}}
			>
				<span
					style={{
						color: props.timeLabelColor,
						...timeLabelFont,
					}}
				>
					{"Local Time:"}
				</span>
				<span
					style={{
						display: "block",
					}}
				>
					<TimeWithFade
						time={timePart}
						fontSize={timeFontSize}
						color={timeColor}
					/>
					{ampmPart && (
						<span
							style={{
								color: timeColor,
							}}
						>
							{" "}
							{ampmPart}
						</span>
					)}
				</span>
			</span>
			<span
				style={{
					...statusFont,
					fontSize: statusFontSize,
					color: statusColor,
					marginTop: 4,
					width: "100%",
					display: "block",
					textAlign: "left",
				}}
			>
				<span
					style={{
						color: statusLabelColor,
						display: "block",
						marginBottom: 2,
						...statusLabelFont,
					}}
				>
					{props.statusLabelText || "N8 is currently:"}
				</span>
				<span
					style={{
						position: "relative",
						display: "block",
						minWidth: 80,
						minHeight: statusFontSize * 1.2,
						marginTop: 0,
					}}
				>
					<b
						style={{
							color: statusPhraseColor,
						}}
					>
						{scrambled}
					</b>
				</span>
			</span>
		</div>
	);
}
addPropertyControls(DenverTimeStatus, {
	timeLabelColor: {
		type: ControlType.Color,
		title: "Time Label Color",
		defaultValue: "#666666",
		description: "Color for the 'Local Time:' label",
	},
	timeLabelFont: {
		type: ControlType.Font,
		title: "Time Label Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			variant: "Medium",
			fontSize: "14px",
			letterSpacing: "-0.01em",
			lineHeight: "1.2em",
		},
	},
	statusRules: {
		type: ControlType.Array,
		title: "Status Rules",
		control: {
			type: ControlType.Object,
			controls: {
				label: {
					type: ControlType.String,
					title: "Label",
					defaultValue: "Making coffee",
				},
				startHour: {
					type: ControlType.Number,
					title: "Start Hour",
					defaultValue: 6,
					min: 0,
					max: 23,
					step: 1,
					unit: "h",
				},
				endHour: {
					type: ControlType.Number,
					title: "End Hour",
					defaultValue: 9,
					min: 1,
					max: 24,
					step: 1,
					unit: "h",
				},
			},
		},
		defaultValue: [
			{
				label: "Making coffee",
				startHour: 6,
				endHour: 9,
			},
			{
				label: "Grabbing lunch",
				startHour: 12,
				endHour: 13,
			},
			{
				label: "Reading a book",
				startHour: 17,
				endHour: 24,
			},
			{
				label: "Working",
				startHour: 9,
				endHour: 12,
			},
			{
				label: "Working",
				startHour: 13,
				endHour: 17,
			},
		],
	},
	background: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "#FFFFFF",
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Radius",
		defaultValue: 8,
		min: 0,
		max: 32,
	},
	timeFont: {
		type: ControlType.Font,
		title: "Time Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			variant: "Semibold",
			letterSpacing: "-0.01em",
			lineHeight: "1.2em",
		},
	},
	timeFontSize: {
		type: ControlType.Number,
		title: "Time Size",
		defaultValue: 22,
		min: 10,
		max: 80,
		step: 1,
		unit: "px",
	},
	timeColor: {
		type: ControlType.Color,
		title: "Time Color",
		defaultValue: "#000000",
	},
	statusFont: {
		type: ControlType.Font,
		title: "Status Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			variant: "Medium",
			letterSpacing: "-0.01em",
			lineHeight: "1.2em",
		},
	},
	statusFontSize: {
		type: ControlType.Number,
		title: "Status Size",
		defaultValue: 18,
		min: 10,
		max: 80,
		step: 1,
		unit: "px",
	},
	statusColor: {
		type: ControlType.Color,
		title: "Status Phrase Color",
		defaultValue: "#000000",
		description: "Color for the status phrase (e.g., 'Making coffee')",
	},
	statusLabelColor: {
		type: ControlType.Color,
		title: "Status Label Color",
		defaultValue: "#666666",
		description: "Color for 'N8 is currently:' label",
	},
	statusLabelFont: {
		type: ControlType.Font,
		title: "Status Label Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			variant: "Medium",
			fontSize: "18px",
			letterSpacing: "-0.01em",
			lineHeight: "1.2em",
		},
	},
	statusPhraseColor: {
		type: ControlType.Color,
		title: "Phrase Color",
		defaultValue: "#0070F3",
		description: "Color for the status phrase text (e.g., 'Making coffee')",
	},
	statusLabelText: {
		type: ControlType.String,
		title: "Status Label Text",
		defaultValue: "N8 is currently:",
		description: "Text for the status label above the status phrase.",
	},
	replayAnimation: {
		type: ControlType.Boolean,
		title: "Replay Animation",
		defaultValue: false,
		enabledTitle: "Replay",
		disabledTitle: "Idle",
		description: "Replay the blur-in animation for the status phrase",
	},
	scrambleDuration: {
		type: ControlType.Number,
		title: "Scramble Duration",
		defaultValue: 700,
		min: 100,
		max: 3e3,
		step: 50,
		unit: "ms",
		description: "Duration of the scramble animation in milliseconds",
	},
	scrambleChars: {
		type: ControlType.String,
		title: "Scramble Chars",
		defaultValue:
			"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*",
		description: "Characters used for the scramble animation",
	},
	use24Hour: {
		type: ControlType.Boolean,
		title: "24-Hour Time",
		defaultValue: false,
		enabledTitle: "24h",
		disabledTitle: "12h",
		description: "Toggle between 12-hour and 24-hour time formats",
	},
	bottomPadding: {
		type: ControlType.Number,
		title: "Bottom Padding",
		defaultValue: 0,
		min: 0,
		max: 100,
		step: 1,
		unit: "px",
		description: "Padding at the bottom of the component",
	},
});

// virtual:denver-time-status
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b2c20ae091a272c0c9ae99ca80cdd041b3dba209ff907e30868b68247f89562e"
			}
			locale={locale}
			locales={locales}
		>
			<DenverTimeStatus {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DenverTimeStatusFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b2c20ae091a272c0c9ae99ca80cdd041b3dba209ff907e30868b68247f89562e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={DenverTimeStatus}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, DenverTimeStatus);
var denver_time_status_default = ComponentWithRoot;
export { denver_time_status_default as default };
