// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b2c20ae091a272c0 "STUDIO FINITY", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'X' | 'Rosa' | 'Bach' | 'Jobs' | 'MJ' | 'Ichiro' | 'Virgil' | 'Dietrich' | 'Augustine' | 'CS' | 'Lee' | 'Coco' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-XUJTH4GZ.js";
import { routes } from "./chunks/chunk-YRAVOFDK.js";

// virtual:hover-cursor-for-rules
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "BLGF6sx33",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b2c20ae091a272c0c9ae99ca80cdd041b3dba209ff907e30868b68247f89562e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HoverCursorForRulesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b2c20ae091a272c0c9ae99ca80cdd041b3dba209ff907e30868b68247f89562e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var hover_cursor_for_rules_default = ComponentWithRoot;
export { hover_cursor_for_rules_default as default };
