// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b2c20ae091a272c0 "STUDIO FINITY", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Tablet' | 'Mobile' // Variant
 * text?: string // Text
 * onnJiZ4nNZIChange?: any // onnJiZ4nNZIChange
 * number?: string // Number
 * onDhMIVVvPcChange?: any // onDhMIVVvPcChange
}} Props

 */
import {
	className,
	css,
	fonts,
	stdin_default,
} from "./chunks/chunk-XUJTH4GZ.js";
import { routes } from "./chunks/chunk-YRAVOFDK.js";

// virtual:hover-rules
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/YbDXEszQKNTi6CZyovGP/GMQxblWrX5LXV8EUqX6Z/RkRAYcB1G.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	forwardLoader,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/4NJ1MAvT2ItMJciFw2EK/8ULmyQ231ezlUREn2Kow/DVNaFBiF7.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Stack Sans Text-regular",
	"GF;Stack Sans Text-regular",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Stack Sans Text",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "Stack Sans Text",
				url: "https://fonts.gstatic.com/s/stacksanstext/v1/kJEkBuAJ-Q0hiGPmzHEu345X1JJNBpRJ3RPan47MNg-KJOhyGgKF1a0.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	`.framer-8DNPm .framer-styles-preset-jsmy7k:not(.rich-text-wrapper), .framer-8DNPm .framer-styles-preset-jsmy7k.rich-text-wrapper p { --framer-font-family: "Stack Sans Text", "Stack Sans Text Placeholder", sans-serif; --framer-font-family-bold: "Stack Sans Text", "Stack Sans Text Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-8DNPm .framer-styles-preset-jsmy7k:not(.rich-text-wrapper), .framer-8DNPm .framer-styles-preset-jsmy7k.rich-text-wrapper p { --framer-font-family: "Stack Sans Text", "Stack Sans Text Placeholder", sans-serif; --framer-font-family-bold: "Stack Sans Text", "Stack Sans Text Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-8DNPm .framer-styles-preset-jsmy7k:not(.rich-text-wrapper), .framer-8DNPm .framer-styles-preset-jsmy7k.rich-text-wrapper p { --framer-font-family: "Stack Sans Text", "Stack Sans Text Placeholder", sans-serif; --framer-font-family-bold: "Stack Sans Text", "Stack Sans Text Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className2 = "framer-8DNPm";

// /:https://framerusercontent.com/modules/YbDXEszQKNTi6CZyovGP/GMQxblWrX5LXV8EUqX6Z/RkRAYcB1G.js
var enabledGestures = {
	pn0kR3oHk: {
		hover: true,
	},
};
var cycleOrder = ["pn0kR3oHk", "EVDerwsoe", "xswEbBgVk"];
var serializationHash = "framer-cqwg3";
var variantClassNames = {
	EVDerwsoe: "framer-v-of6t7o",
	pn0kR3oHk: "framer-v-70dn6h",
	xswEbBgVk: "framer-v-zwokxt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "pn0kR3oHk",
	Mobile: "xswEbBgVk",
	Tablet: "EVDerwsoe",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, number, text, width, ...props }) => {
	return {
		...props,
		DhMIVvvPc: number ?? props.DhMIVvvPc ?? "001",
		nJiZ4nNZi: text ?? props.nJiZ4nNZi ?? "Never take no for an answer.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "pn0kR3oHk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		nJiZ4nNZi: nJiZ4nNZi2,
		DhMIVvvPc: DhMIVvvPc2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "pn0kR3oHk",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.main
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-70dn6h",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"pn0kR3oHk"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-845c69d1-5897-4dac-bab8-cae9a98aa49a, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								"pn0kR3oHk-hover": {
									"data-framer-name": void 0,
								},
								EVDerwsoe: {
									"data-framer-name": "Tablet",
								},
								xswEbBgVk: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-129fsl7"}
							layoutDependency={layoutDependency}
							layoutId={"zRnT8hdLn"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-f56tgi"}
								data-framer-name={"Number"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Z5GVwbeUj"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0))",
									"--framer-paragraph-spacing": "0px",
									opacity: 0.1,
								}}
								text={DhMIVvvPc2}
								variants={{
									"pn0kR3oHk-hover": {
										opacity: 1,
									},
									EVDerwsoe: {
										opacity: 1,
									},
									xswEbBgVk: {
										opacity: 1,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										xswEbBgVk: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1pp51bx"}
														data-styles-preset={"Vx1W8nsoP"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0)))",
														}}
													>
														{"001"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-jsmy7k"}
										data-styles-preset={"DVNaFBiF7"}
										dir={"auto"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0)))",
										}}
									>
										{"001"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-qh4fa4"}
								layoutDependency={layoutDependency}
								layoutId={"cSG1QKdPP"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-10bm878"}
									data-framer-name={"Number"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"EuEQuMKfU"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
										opacity: 0.1,
									}}
									variants={{
										"pn0kR3oHk-hover": {
											opacity: 1,
										},
										EVDerwsoe: {
											opacity: 1,
										},
										xswEbBgVk: {
											opacity: 1,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											xswEbBgVk: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1pp51bx"}
															data-styles-preset={"Vx1W8nsoP"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0)))",
															}}
														>
															{"/"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-jsmy7k"}
											data-styles-preset={"DVNaFBiF7"}
											dir={"auto"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0)))",
											}}
										>
											{"/"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1v42owc"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"vvUXRhT5v"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0))",
									"--framer-paragraph-spacing": "0px",
									opacity: 0.1,
								}}
								text={nJiZ4nNZi2}
								variants={{
									"pn0kR3oHk-hover": {
										opacity: 1,
									},
									EVDerwsoe: {
										opacity: 1,
									},
									xswEbBgVk: {
										opacity: 1,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										xswEbBgVk: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1pp51bx"}
														data-styles-preset={"Vx1W8nsoP"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0)))",
														}}
													>
														{"Never take no for an answer."}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-jsmy7k"}
										data-styles-preset={"DVNaFBiF7"}
										dir={"auto"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-32c6196e-4f17-40c8-8cf8-4163456ea61a, rgb(0, 0, 0)))",
										}}
									>
										{"Never take no for an answer."}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.main>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-cqwg3.framer-lzdz6u, .framer-cqwg3 .framer-lzdz6u { display: block; }",
	".framer-cqwg3.framer-70dn6h { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 11px; height: min-content; justify-content: center; max-width: 1920px; overflow: visible; padding: 2px 0px 2px 0px; position: relative; width: 1200px; }",
	".framer-cqwg3 .framer-129fsl7 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-cqwg3 .framer-f56tgi { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 64px; word-break: break-word; word-wrap: break-word; }",
	".framer-cqwg3 .framer-qh4fa4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 2px 0px 0px; position: relative; width: min-content; }",
	".framer-cqwg3 .framer-10bm878 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-cqwg3 .framer-1v42owc { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-cqwg3.framer-v-of6t7o.framer-70dn6h, .framer-cqwg3.framer-v-zwokxt.framer-70dn6h { cursor: unset; }",
	".framer-cqwg3.framer-v-zwokxt .framer-129fsl7 { gap: 4px; }",
	".framer-cqwg3.framer-v-zwokxt .framer-f56tgi { width: 28px; }",
	...css2,
	...css,
];
var FramerRkRAYcB1G = withCSS(Component, css3, "framer-cqwg3");
var stdin_default2 = FramerRkRAYcB1G;
FramerRkRAYcB1G.displayName = "Hover Rules";
FramerRkRAYcB1G.defaultProps = {
	height: 39,
	width: 1200,
};
addPropertyControls(FramerRkRAYcB1G, {
	variant: {
		options: ["pn0kR3oHk", "EVDerwsoe", "xswEbBgVk"],
		optionTitles: ["Variant 1", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	nJiZ4nNZi: {
		defaultValue: "Never take no for an answer.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	onnJiZ4nNZiChange: {
		changes: "nJiZ4nNZi",
		type: ControlType.ChangeHandler,
	},
	DhMIVvvPc: {
		defaultValue: "001",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	onDhMIVvvPcChange: {
		changes: "DhMIVvvPc",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerRkRAYcB1G,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerRkRAYcB1G.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:hover-rules
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "xswEbBgVk",
	md: "EVDerwsoe",
	xl: "pn0kR3oHk",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b2c20ae091a272c0c9ae99ca80cdd041b3dba209ff907e30868b68247f89562e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HoverRulesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b2c20ae091a272c0c9ae99ca80cdd041b3dba209ff907e30868b68247f89562e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var hover_rules_default = ComponentWithRoot;
export { hover_rules_default as default };
